name: build
on: pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Docker Build
        run: docker compose build
