name: remote ssh command
on: [push]
jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Prepare Env
      run : docker system prune --volumes -af
    - name: Build Image
      run: |
          docker compose build
          docker image ls
          docker tag $(docker images uwpath_backend --format "{{.ID}}") uwpathdocker/uwpath_backend:int
          docker push uwpathdocker/uwpath_backend:int
    
