name: remote ssh command
on: [push]
jobs:
  build:
    name: deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: ssh ubuntu@${{secrets.UWPATH_IP}} --i ${{secrets.UWPATH_PRIVATE_KEY}}
    - run: echo ls
    
