name: remote ssh command
on: [push]
jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Prepare Env
      run : docker rmi $(docker images -a -q)
    - name: Build Image
      run: |
          docker compose build
          docker image ls
    
