name: remote ssh command
on: [push]
jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: echo ${{secrets.UWPATH_IP}}
    - run: echo ${{secrets.UWPATH_PRIVATE_KEY}} > id_uwpath_parallel.key
    - run: ssh ubuntu@${{secrets.UWPATH_IP}} -i id_uwpath_parallel.key
    - run: ls
    
