name: remote ssh command
on: [push]
jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: pwd
    - name: Create SSH Key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo ${{ secrets.UWPATH_PRIVATE_KEY }} > ~/.ssh/id_rsa
        ssh-keyscan -H 129.153.61.57 > ~/.ssh/known_hosts
    - name: SSH Into Parallel Server
      run: ssh ubuntu@${{ secrets.UWPATH_IP }}
    - run: ls
    
