name: gcp_deploy_backend_dev
on:
  push:
    branches:
      - int
      - pipline-setup

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: G-Cloud Authenticate
        uses: 'google-github-actions/auth@v0'
        with: 
          credentials-json: ${{ secrets.GCP_SERVICE_CREDENTIALS_DEV }}
      - uses: actions/checkout@v3
      - name: Docker Build
        env:
          IMAGE_NAME: ${{ secrets.GCP_IMAGE_NAME_DEV }}
        run: docker build -t "$IMAGE_NAME" .
      - name: Push to Container Registry
        env:
          IMAGE_NAME: ${{ secrets.GCP_IMAGE_NAME_DEV }}
        run: docker push "$IMAGE_NAME"
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          image: ${{ secrets.GCP_IMAGE_NAME_DEV }}
          service: ${{ secrets.GCP_IMAGE_NAME_DEV }}
      - name: Clean Env
        if: always()
        run: docker system prune --volumes -af


