name: gcp_deploy_backend_dev
on:
  push:
    branches:
      - int
      - pipeline-setup

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: G-Cloud Authenticate
        id: gcloud_auth
        uses: 'google-github-actions/auth@v0'
        with: 
          token_format: access_token
          credentials_json: ${{ secrets.GCP_SERVICE_CREDENTIALS_DEV }}
      - name: G-Cloud Docker Login
        run: |-
          echo '${{ steps.gcloud_auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io
      - name: Docker Build
        env:
          IMAGE_NAME: ${{ secrets.GCP_IMAGE_NAME_DEV }}
        run: docker build -t "$IMAGE_NAME" .
      - name: Push to Container Registry
        env:
          IMAGE_NAME: ${{ secrets.GCP_IMAGE_NAME_DEV }}
        run: docker push "$IMAGE_NAME"
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          image: ${{ secrets.GCP_IMAGE_NAME_DEV }}
          service: ${{ secrets.GCP_IMAGE_NAME_DEV }}
      - name: Clean Env
        if: always()
        run: docker system prune --volumes -af


